"""Convert the approved gold arrow frames into src/arrow_atlas.inc.

Input: the handoff's idle/frames directory (48 RGBA frames, 300x300, identical alpha).
The shimmer is one warm pulse, so it is stored as its calm frame (000), its peak
frame (024) and a 48-step blend curve fitted to every frame. Frames are reduced to
128x128 with premultiplied alpha; the plugin derives the body/diamond parts and
mip levels at load time.
"""
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CELL = 128
FRAMES = 48


def load(path):
    image = Image.open(path).convert('RGBA')
    if image.size != (300, 300):
        raise ValueError(f'expected a 300x300 frame: {path}')
    return image


def shrink(image):
    # Premultiplied resampling keeps transparent black from darkening the edges.
    return image.convert('RGBa').resize((CELL, CELL), Image.LANCZOS).convert('RGBA')


def blend_curve(frames):
    calm, peak = frames[0].get_flattened_data(), frames[24].get_flattened_data()
    pairs = [(c, p) for c, p in zip(calm, peak) if c[3] > 8]
    weights = []
    for frame in frames:
        pixels = frame.get_flattened_data()
        top = bottom = 0.0
        for (c, p), f in zip(pairs, (px for px, cp in zip(pixels, calm) if cp[3] > 8)):
            for k in range(3):
                d = p[k] - c[k]
                top += (f[k] - c[k]) * d
                bottom += d * d
        weights.append(max(0.0, min(1.0, top / bottom)) if bottom else 0.0)
    return weights


def main():
    source = Path(sys.argv[1])
    frames = [load(source / f'frame-{i:03d}.png') for i in range(FRAMES)]
    if len({frame.getchannel('A').tobytes() for frame in frames}) != 1:
        raise ValueError('frames must share one alpha channel')
    weights = blend_curve(frames)
    cells = [shrink(frames[0]), shrink(frames[24])]
    lines = ['// Generated by tools/prepare_arrow.py from the approved gold arrow (made with ChatGPT).',
             '// Two 128x128 straight-alpha ARGB frames: calm, then shimmer peak.',
             f'constexpr unsigned ArrowCell = {CELL};',
             'constexpr std::uint32_t ArrowFrames[] = {']
    for cell in cells:
        pixels = [f'0x{a:02X}{r:02X}{g:02X}{b:02X}u' for r, g, b, a in cell.get_flattened_data()]
        lines += [','.join(pixels[i:i + 16]) + ',' for i in range(0, len(pixels), 16)]
    lines += ['};', '// Peak weight for each 40 ms step of the 1.92 s shimmer.',
              'constexpr float ArrowShimmer[] = {' + ','.join(f'{w:.4f}f' for w in weights) + '};', '']
    (ROOT / 'src' / 'arrow_atlas.inc').write_text('\n'.join(lines), encoding='utf-8')
    print('weights', ' '.join(f'{w:.3f}' for w in weights))


if __name__ == '__main__':
    main()
