"""Build standalone trait artwork from a pinned upstream MobDB checkout.

Development-only regeneration: Python + Pillow. No Lua is executed or shipped.
"""
import argparse
from pathlib import Path
import shutil
import subprocess

REVISION = 'eee7e1ad5d0a49eb667f1f88602d9fce76276330'
FLAGS = ('TrueSight', 'Sight', 'Sound', 'Magic', 'JA', 'Blood', 'Link')
# Icon order shared with the generated Phoenix damage bit fields.
MODIFIERS = ('Slashing', 'Piercing', 'H2H', 'Impact', 'Fire', 'Ice', 'Wind', 'Earth', 'Lightning', 'Water', 'Light', 'Dark')
ROOT = Path(__file__).resolve().parents[1]


def generate(source):
    from PIL import Image
    revision = subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip()
    if revision != REVISION:
        raise ValueError('Expected pinned MobDB revision ' + REVISION)
    # Refuse modified source inputs; provenance must describe what was compiled.
    if subprocess.check_output(['git', '-C', str(source), 'status', '--porcelain'], text=True).strip():
        raise ValueError('Upstream checkout has local changes')
    # Row 0: trait icons and a white cell; rows 1-2: modifier icons.
    atlas = Image.new('RGBA', (256, 96), (255, 255, 255, 0))
    for i, flag in enumerate(FLAGS):
        icon = Image.open(source / 'icons' / (flag + '.png')).convert('RGBA')
        if icon.size != (32, 32):
            raise ValueError('Expected original 32x32 icon: ' + flag)
        atlas.paste(icon, (i * 32, 0))
    # Final cell is white for the outlined aggression strip.
    atlas.paste((255, 255, 255, 255), (224, 0, 256, 32))
    for i, modifier in enumerate(MODIFIERS):
        icon = Image.open(source / 'icons' / (modifier + '.png')).convert('RGBA')
        if icon.size != (32, 32):
            raise ValueError('Expected original 32x32 icon: ' + modifier)
        atlas.paste(icon, (i % 8 * 32, (1 + i // 8) * 32))
    pixels = [f'0x{a:02X}{r:02X}{g:02X}{b:02X}u' for r, g, b, a in atlas.getdata()]
    atlas_text = '// Generated from MobDB icons; MIT, see licenses/MobDB.txt.\nconstexpr std::uint32_t TraitPixels[] = {\n'
    atlas_text += '\n'.join(','.join(pixels[i:i+16]) + ',' for i in range(0, len(pixels), 16)) + '\n};\n'
    (ROOT / 'src/trait_atlas.inc').write_text(atlas_text, encoding='utf-8')
    (ROOT / 'licenses').mkdir(exist_ok=True)
    shutil.copyfile(source / 'LICENSE', ROOT / 'licenses/MobDB.txt')
    print('Regenerated MobDB icon atlas (monster data is generated by prepare_phoenix_traits.py).')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    generate(parser.parse_args().source)
