"""Generate embedded traits from the standalone compiled Phoenix SQLite database.

No server scripts are executed. Element/status resistance ranks are deliberately
not converted to damage multipliers. Existing artwork is generated separately.
"""
import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import shutil
import sqlite3

ROOT = Path(__file__).resolve().parents[1]
VIEW = 'configured_overlays'
REVISION = '5b1282e9277ebed506a9bd03490cbc6bc1cdd75b'
PHYSICAL = ('slashing', 'piercing', 'h2h', 'blunt')
ELEMENTS = ('fire', 'ice', 'wind', 'earth', 'thunder', 'water', 'light', 'dark')


def traits(record):
    senses = record['detection'] or []
    bits = 0
    for sense, bit in [('sight', 2), ('hearing', 4), ('magic', 8),
                       ('ability', 16), ('lowhp', 32)]:
        if sense in senses:
            bits |= bit
    if bits & 2 and record['true_detection']:
        bits = (bits & ~2) | 1
    if record['links']:
        bits |= 64
    if record['aggressive'] is not None:
        bits |= 256 | (512 if record['aggressive'] else 0)
    resists = record['attributes'].get('resists', {})
    mods = record['attributes'].get('mods', {})
    physical = resists.get('dmg_physical', {})
    magic = resists.get('dmg_magic', {})
    # Phoenix sets resistance modifiers, then adds attributes.mods. Only type-
    # specific SDT is represented here; global DT, ranks and status immunity are
    # separate mechanics and are not claimed by these icons.
    values = [physical.get(k, 0) + mods.get(m, 0) for k, m in zip(
        PHYSICAL, ('slash_sdt', 'pierce_sdt', 'hth_sdt', 'impact_sdt'))]
    all_magic = magic.get('all', 0) + mods.get('udmgmagic', 0)
    values += [(10000 + magic.get(k, 0) + mods.get(k + '_sdt', 0))
               * (10000 + all_magic) - 100000000 for k in ELEMENTS]
    weak = sum(1 << i for i, v in enumerate(values) if v > 0)
    resist = sum(1 << i for i, v in enumerate(values) if v < 0)
    return bits, weak, resist


def display_name(record, template):
    name = template.get('display_name')
    if not name:
        name = record['name']
        script = record.get('script')
        # Templates distinguish job/zone variants with suffixes. The matching
        # script label supplies their common name (e.g. Enchanted_Bones_war).
        if script and name.startswith(script + '_'):
            name = script
    return name.replace('_', ' ')[:24]


def generate(compiled):
    manifest = json.loads((compiled / 'manifest.json').read_text())
    if manifest['revision'] != REVISION:
        raise ValueError('Review mappings before updating the pinned Phoenix revision')
    db = compiled / 'phoenix-mobdb.sqlite'
    connection = sqlite3.connect(db.resolve().as_uri() + '?mode=ro', uri=True)
    templates = {(z, n): json.loads(r) for z, n, r in connection.execute(
        'SELECT zone,name,record_json FROM templates WHERE view=?', (VIEW,))}
    groups = defaultdict(lambda: defaultdict(list))
    count = 0
    for (raw,) in connection.execute('SELECT record_json FROM mobs WHERE view=? ORDER BY mob_id', (VIEW,)):
        record = json.loads(raw)
        if record['template'] is None:
            continue  # Reserved script slots have no static monster definition.
        name = display_name(record, templates[(record['zone'], record['template'])])
        groups[record['zone_id']][name].append((record['entity_index'], traits(record)))
        count += 1
    connection.close()
    names, indices, zones = [], [], {}
    ambiguous = 0
    for zone, by_name in sorted(groups.items()):
        first_name, first_index = len(names), len(indices)
        local_indices = []
        for name, entries in sorted(by_name.items()):
            variants = {value for _, value in entries}
            if len(variants) == 1:
                names.append((name, 0, entries[0][1]))
            else:
                # No guessed name default when same-named spawns differ.
                ambiguous += 1
                local_indices.extend((name, index, value) for index, value in entries)
        indices.extend(sorted(local_indices, key=lambda r: r[1]))
        zones[zone] = (first_name, len(names) - first_name, first_index, len(indices) - first_index)
    out = ['// Generated by tools/prepare_phoenix_traits.py; Phoenix data, GPL-3.0.',
           '// See licenses/Phoenix-MobDB.txt and licenses/Phoenix-MobDB-SOURCE.md.',
           f'// Revision {REVISION}; view {VIEW}; static reference, not live verified.']
    for label, rows in [('NameRows', names), ('IndexRows', indices)]:
        out.append(f'constexpr TraitRow {label}[] = {{')
        for name, index, (bits, weak, resist) in rows:
            out.append('{' + json.dumps(name, ensure_ascii=True) + f', {bits}, {index}, {weak}, {resist}' + '},')
        out.append('};')
    out.append('constexpr TraitZone Zones[] = {')
    out.extend('{' + ','.join(map(str, zones.get(z, (0, 0, 0, 0)))) + '},'
               for z in range(max(zones) + 1))
    out.append('};\n')
    (ROOT / 'src/trait_data.inc').write_text('\n'.join(out), encoding='utf-8')
    shutil.copyfile(compiled / 'UPSTREAM-LICENSE.txt', ROOT / 'licenses/Phoenix-MobDB.txt')
    print(json.dumps(dict(revision=REVISION, view=VIEW, records=count, names=len(names),
                         index_rows=len(indices), ambiguous_names=ambiguous,
                         database_sha256=hashlib.sha256(db.read_bytes()).hexdigest()), indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('compiled', type=Path)
    generate(parser.parse_args().compiled)
