"""Build standalone trait data/artwork from a pinned upstream MobDB checkout.

Development-only regeneration: Python + Pillow. No Lua is executed or shipped.
"""
import argparse
import json
from pathlib import Path
import re
import shutil
import subprocess

REVISION = 'eee7e1ad5d0a49eb667f1f88602d9fce76276330'
FLAGS = ('TrueSight', 'Sight', 'Sound', 'Magic', 'JA', 'Blood', 'Link')
ROOT = Path(__file__).resolve().parents[1]
STRING = r"'((?:\\.|[^'\\])*)'"


def lua_string(value):
    return re.sub(r"\\(['\\])", r'\1', value)


def generate(source):
    from PIL import Image
    revision = subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip()
    if revision != REVISION:
        raise ValueError('Expected pinned MobDB revision ' + REVISION)
    # Refuse modified source inputs; provenance must describe what was compiled.
    if subprocess.check_output(['git', '-C', str(source), 'status', '--porcelain'], text=True).strip():
        raise ValueError('Upstream checkout has local changes')
    names, indices, zones = [], [], {}
    source_rows = 0
    for path in sorted((source / 'data').glob('*.lua'), key=lambda p: int(p.stem)):
        by_name, by_index = {}, {}
        section = None
        for line in path.read_text(encoding='utf-8-sig').splitlines():
            if re.match(r'\s*Names\s*=', line):
                section = 'names'
            elif re.match(r'\s*Indices\s*=', line):
                section = 'indices'
            if not line.lstrip().startswith('['):
                continue
            match = re.match(r'\s*\[(.*?)\]\s*=\s*\{\s*Name=' + STRING + r',', line)
            if not match or section is None:
                raise ValueError(f'Unsupported data row in {path}: {line}')
            key, name = match.group(1), lua_string(match.group(2))
            bits = 0
            for bit, flag in enumerate(FLAGS):
                value = re.search(r'\b' + flag + r'=(true|false)\b', line)
                if value and value.group(1) == 'true':
                    bits |= 1 << bit
            if bits & 1:
                bits &= ~2  # True sight supersedes ordinary sight.
            aggro = re.search(r'\bAggro=(true|false)\b', line)
            if aggro:
                bits |= 0x100
                if aggro.group(1) == 'true':
                    bits |= 0x200
            if section == 'names':
                key_match = re.fullmatch(STRING, key)
                if not key_match or lua_string(key_match.group(1)) != name or name in by_name:
                    raise ValueError(f'Unexpected name key in {path}: {key}')
                by_name[name] = bits
            else:
                index = int(key)
                if index in by_index or not 0 <= index < 0x900:
                    raise ValueError(f'Unexpected index in {path}: {key}')
                by_index[index] = (name, bits)
            source_rows += 1
        first_name, first_index = len(names), len(indices)
        names.extend((name, bits, 0) for name, bits in sorted(by_name.items()))
        indices.extend((name, bits, index) for index, (name, bits) in sorted(by_index.items())
                       if by_name.get(name) != bits)
        zones[int(path.stem)] = (first_name, len(names) - first_name, first_index, len(indices) - first_index)
    out = ['// Generated by tools/prepare_traits.py; MobDB MIT, see licenses/MobDB.txt.',
           f'// Upstream {REVISION}; data only, no addon implementation.',
           'constexpr TraitRow NameRows[] = {']
    def row(value):
        name, bits, index = value
        return '{' + json.dumps(name, ensure_ascii=True) + f', {bits}, {index}' + '},'
    out.extend(map(row, names))
    out += ['};', 'constexpr TraitRow IndexRows[] = {']
    out.extend(map(row, indices))
    out += ['};', 'constexpr TraitZone Zones[] = {']
    out.extend('{' + ','.join(map(str, zones.get(z, (0, 0, 0, 0)))) + '},' for z in range(max(zones) + 1))
    out += ['};', '']
    (ROOT / 'src/trait_data.inc').write_text('\n'.join(out), encoding='utf-8')
    atlas = Image.new('RGBA', (256, 32), (255, 255, 255, 0))
    for i, flag in enumerate(FLAGS):
        icon = Image.open(source / 'icons' / (flag + '.png')).convert('RGBA')
        if icon.size != (32, 32):
            raise ValueError('Expected original 32x32 icon: ' + flag)
        atlas.paste(icon, (i * 32, 0))
    # Final cell is white for the outlined aggression strip.
    atlas.paste((255, 255, 255, 255), (224, 0, 256, 32))
    pixels = [f'0x{a:02X}{r:02X}{g:02X}{b:02X}u' for r, g, b, a in atlas.getdata()]
    atlas_text = '// Generated from MobDB icons; MIT, see licenses/MobDB.txt.\nconstexpr std::uint32_t TraitPixels[] = {\n'
    atlas_text += '\n'.join(','.join(pixels[i:i+16]) + ',' for i in range(0, len(pixels), 16)) + '\n};\n'
    (ROOT / 'src/trait_atlas.inc').write_text(atlas_text, encoding='utf-8')
    (ROOT / 'licenses').mkdir(exist_ok=True)
    shutil.copyfile(source / 'LICENSE', ROOT / 'licenses/MobDB.txt')
    print(json.dumps(dict(revision=revision, zones=len(zones), source_rows=source_rows,
                          names=len(names), distinct_index_overrides=len(indices), atlas_bytes=256*32*4), indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    generate(parser.parse_args().source)
